apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: es66han66/kub-demo-users:1
        env:
          - name: AUTH_ADDRESS
            value: "10.100.206.138"
